name: learn-web

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./workspace:/workspace
    ports:
      - "8000:8000"
    command:
      [
        "serve-web",
        "--host",
        "0.0.0.0",
        "--accept-server-license-terms",
        "--connection-token",
        "<secret>",
      ]

  nginx:
    image: nginx:alpine
    volumes:
      - ./workspace:/usr/share/nginx/html
    ports:
      - "8080:80"
